# Basic Operations

In [2]:
5+7

ans =  12


In [3]:
6/4

ans =  1.5000


In [4]:
5-6

ans = -1


In [5]:
2^4

ans =  16


In [6]:
5*5


ans =  25


In [7]:
sin(5)

ans = -0.95892


In [8]:
cos(5)

ans =  0.28366


In [9]:
tan(pi)

ans =   -1.2246e-16


In [10]:
pi

ans =  3.1416


In [11]:
format long

In [12]:
pi

ans =  3.14159265358979


In [13]:
format short

In [14]:
exp(1)

ans =  2.7183


In [15]:
log(exp(1))

ans =  1


In [16]:
log10(10)

ans =  1


In [17]:
sinh(4)

ans =  27.290


In [18]:
tanh(3)

ans =  0.99505


# vector and matrix

In [19]:
x=[1 2]

x =

   1   2



In [20]:
y=[3;4]

y =

   3
   4



In [21]:
y'

ans =

   3   4



In [22]:
x+y

ans =

   4   5
   5   6



In [23]:
x

x =

   1   2



In [24]:
y

y =

   3
   4



In [25]:
x.*y

ans =

   3   6
   4   8



In [26]:
y=[3 4]

y =

   3   4



In [27]:
x+y

ans =

   4   6



In [28]:
A=[1 2; 3 4]

A =

   1   2
   3   4



In [29]:
B = [5 6; 7 8]

B =

   5   6
   7   8



In [30]:
C=B^(-1)

C =

  -4.0000   3.0000
   3.5000  -2.5000



In [31]:
A*C

ans =

   3.00000  -2.00000
   2.00000  -1.00000



In [32]:
B*C

ans =

   1.00000   0.00000
   0.00000   1.00000



In [33]:
inv(B)

ans =

  -4.0000   3.0000
   3.5000  -2.5000



In [34]:
det(B)

ans = -2.0000


In [35]:
eigvector(A)

error: 'eigvector' undefined near line 1 column 1


In [36]:
help eig

'eig' is a built-in function from the file libinterp/corefcn/eig.cc

 -- Built-in Function: LAMBDA = eig (A)
 -- Built-in Function: LAMBDA = eig (A, B)
 -- Built-in Function: [V, LAMBDA] = eig (A)
 -- Built-in Function: [V, LAMBDA] = eig (A, B)
     Compute the eigenvalues (and optionally the eigenvectors) of a
     matrix or a pair of matrices

     The algorithm used depends on whether there are one or two input
     matrices, if they are real or complex, and if they are symmetric
     (Hermitian if complex) or non-symmetric.

     The eigenvalues returned by 'eig' are not ordered.

     See also: eigs, svd.

Additional help for built-in functions and operators is
available in the online version of the manual.  Use the command
'doc <topic>' to search the manual index.

Help and information about Octave is also available on the WWW
at http://www.octave.org and via the help@octave.org
mailing list.


In [37]:
A=[1 2 3; 4 5 6; 7 8 98]

A =

    1    2    3
    4    5    6
    7    8   98



$a_{1,1} \quad   a_{1,2}  \quad  a_{1,3}$

$a_{2,1} \quad   a_{2,2}  \quad  a_{2,3}$

$a_{3,1} \quad   a_{3,2}  \quad  a_{3,3}$

In [38]:
A(1:3,3)

ans =

    3
    6
   98



In [39]:
size(A)

ans =

   3   3



In [40]:
A=zeros(3)

A =

   0   0   0
   0   0   0
   0   0   0



In [41]:
A = eye(4)

A =

Diagonal Matrix

   1   0   0   0
   0   1   0   0
   0   0   1   0
   0   0   0   1



In [42]:
A=rand(4)

A =

   0.606503   0.597362   0.178119   0.201635
   0.014751   0.846308   0.691897   0.922273
   0.349956   0.439387   0.119390   0.155776
   0.497024   0.502699   0.021477   0.264057



In [43]:
x1 = sqrt(100^2 -60^2)
x1*15*(60^2 + x1^2)^(-1/2)

x1 =  80
ans =  12


In [44]:
%plot gnuplot
plottest